/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAguardandoAprovacaoRouteImport } from './routes/_authenticated/aguardando-aprovacao'
import { Route as AuthenticatedConvitesRouteImport } from './routes/_authenticated/convites'
import { Route as AuthenticatedCriarEquipeRouteImport } from './routes/_authenticated/criar-equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEntrarEquipeRouteImport } from './routes/_authenticated/entrar-equipe'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedMusicasRouteImport } from './routes/_authenticated/musicas'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRepertorioRouteImport } from './routes/_authenticated/repertorio'
import { Route as AuthenticatedEventosIdRouteImport } from './routes/_authenticated/eventos.$id'
import { Route as AuthenticatedEventosNovoRouteImport } from './routes/_authenticated/eventos.novo'
import { Route as AuthenticatedEventosIdEditarRouteImport } from './routes/_authenticated/eventos.$id_.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAguardandoAprovacaoRoute =
  AuthenticatedAguardandoAprovacaoRouteImport.update({
    id: '/aguardando-aprovacao',
    path: '/aguardando-aprovacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConvitesRoute = AuthenticatedConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriarEquipeRoute =
  AuthenticatedCriarEquipeRouteImport.update({
    id: '/criar-equipe',
    path: '/criar-equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrarEquipeRoute =
  AuthenticatedEntrarEquipeRouteImport.update({
    id: '/entrar-equipe',
    path: '/entrar-equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusicasRoute = AuthenticatedMusicasRouteImport.update({
  id: '/musicas',
  path: '/musicas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepertorioRoute = AuthenticatedRepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosIdRoute = AuthenticatedEventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosNovoRoute =
  AuthenticatedEventosNovoRouteImport.update({
    id: '/eventos/novo',
    path: '/eventos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosIdEditarRoute =
  AuthenticatedEventosIdEditarRouteImport.update({
    id: '/eventos/$id_/editar',
    path: '/eventos/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/aguardando-aprovacao': typeof AuthenticatedAguardandoAprovacaoRoute
  '/convites': typeof AuthenticatedConvitesRoute
  '/criar-equipe': typeof AuthenticatedCriarEquipeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrar-equipe': typeof AuthenticatedEntrarEquipeRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/musicas': typeof AuthenticatedMusicasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/eventos/$id': typeof AuthenticatedEventosIdRoute
  '/eventos/novo': typeof AuthenticatedEventosNovoRoute
  '/eventos/$id/editar': typeof AuthenticatedEventosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/aguardando-aprovacao': typeof AuthenticatedAguardandoAprovacaoRoute
  '/convites': typeof AuthenticatedConvitesRoute
  '/criar-equipe': typeof AuthenticatedCriarEquipeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrar-equipe': typeof AuthenticatedEntrarEquipeRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/musicas': typeof AuthenticatedMusicasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/eventos/$id': typeof AuthenticatedEventosIdRoute
  '/eventos/novo': typeof AuthenticatedEventosNovoRoute
  '/eventos/$id/editar': typeof AuthenticatedEventosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/aguardando-aprovacao': typeof AuthenticatedAguardandoAprovacaoRoute
  '/_authenticated/convites': typeof AuthenticatedConvitesRoute
  '/_authenticated/criar-equipe': typeof AuthenticatedCriarEquipeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entrar-equipe': typeof AuthenticatedEntrarEquipeRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/musicas': typeof AuthenticatedMusicasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/repertorio': typeof AuthenticatedRepertorioRoute
  '/_authenticated/eventos/$id': typeof AuthenticatedEventosIdRoute
  '/_authenticated/eventos/novo': typeof AuthenticatedEventosNovoRoute
  '/_authenticated/eventos/$id_/editar': typeof AuthenticatedEventosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/agenda'
    | '/aguardando-aprovacao'
    | '/convites'
    | '/criar-equipe'
    | '/dashboard'
    | '/entrar-equipe'
    | '/equipe'
    | '/musicas'
    | '/onboarding'
    | '/perfil'
    | '/repertorio'
    | '/eventos/$id'
    | '/eventos/novo'
    | '/eventos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/agenda'
    | '/aguardando-aprovacao'
    | '/convites'
    | '/criar-equipe'
    | '/dashboard'
    | '/entrar-equipe'
    | '/equipe'
    | '/musicas'
    | '/onboarding'
    | '/perfil'
    | '/repertorio'
    | '/eventos/$id'
    | '/eventos/novo'
    | '/eventos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/_authenticated/agenda'
    | '/_authenticated/aguardando-aprovacao'
    | '/_authenticated/convites'
    | '/_authenticated/criar-equipe'
    | '/_authenticated/dashboard'
    | '/_authenticated/entrar-equipe'
    | '/_authenticated/equipe'
    | '/_authenticated/musicas'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/repertorio'
    | '/_authenticated/eventos/$id'
    | '/_authenticated/eventos/novo'
    | '/_authenticated/eventos/$id_/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aguardando-aprovacao': {
      id: '/_authenticated/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AuthenticatedAguardandoAprovacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/convites': {
      id: '/_authenticated/convites'
      path: '/convites'
      fullPath: '/convites'
      preLoaderRoute: typeof AuthenticatedConvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criar-equipe': {
      id: '/_authenticated/criar-equipe'
      path: '/criar-equipe'
      fullPath: '/criar-equipe'
      preLoaderRoute: typeof AuthenticatedCriarEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrar-equipe': {
      id: '/_authenticated/entrar-equipe'
      path: '/entrar-equipe'
      fullPath: '/entrar-equipe'
      preLoaderRoute: typeof AuthenticatedEntrarEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/musicas': {
      id: '/_authenticated/musicas'
      path: '/musicas'
      fullPath: '/musicas'
      preLoaderRoute: typeof AuthenticatedMusicasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repertorio': {
      id: '/_authenticated/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof AuthenticatedRepertorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/$id': {
      id: '/_authenticated/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof AuthenticatedEventosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/novo': {
      id: '/_authenticated/eventos/novo'
      path: '/eventos/novo'
      fullPath: '/eventos/novo'
      preLoaderRoute: typeof AuthenticatedEventosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/$id_/editar': {
      id: '/_authenticated/eventos/$id_/editar'
      path: '/eventos/$id/editar'
      fullPath: '/eventos/$id/editar'
      preLoaderRoute: typeof AuthenticatedEventosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAguardandoAprovacaoRoute: typeof AuthenticatedAguardandoAprovacaoRoute
  AuthenticatedConvitesRoute: typeof AuthenticatedConvitesRoute
  AuthenticatedCriarEquipeRoute: typeof AuthenticatedCriarEquipeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntrarEquipeRoute: typeof AuthenticatedEntrarEquipeRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedMusicasRoute: typeof AuthenticatedMusicasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRepertorioRoute: typeof AuthenticatedRepertorioRoute
  AuthenticatedEventosIdRoute: typeof AuthenticatedEventosIdRoute
  AuthenticatedEventosNovoRoute: typeof AuthenticatedEventosNovoRoute
  AuthenticatedEventosIdEditarRoute: typeof AuthenticatedEventosIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAguardandoAprovacaoRoute: AuthenticatedAguardandoAprovacaoRoute,
  AuthenticatedConvitesRoute: AuthenticatedConvitesRoute,
  AuthenticatedCriarEquipeRoute: AuthenticatedCriarEquipeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntrarEquipeRoute: AuthenticatedEntrarEquipeRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedMusicasRoute: AuthenticatedMusicasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRepertorioRoute: AuthenticatedRepertorioRoute,
  AuthenticatedEventosIdRoute: AuthenticatedEventosIdRoute,
  AuthenticatedEventosNovoRoute: AuthenticatedEventosNovoRoute,
  AuthenticatedEventosIdEditarRoute: AuthenticatedEventosIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
